-- ============================================
-- Muhasebe Sistem - Initial Database Schema
-- Generated: 2026-01-30
-- Tables: 25
-- ============================================

SET FOREIGN_KEY_CHECKS=0;

-- Table: accounts
CREATE TABLE `accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL,
  `name` varchar(200) NOT NULL,
  `account_type` varchar(50) NOT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `personnel_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_accounts_code` (`code`),
  KEY `ix_accounts_id` (`id`),
  KEY `fk_account_contact` (`contact_id`),
  KEY `fk_account_personnel` (`personnel_id`),
  CONSTRAINT `fk_account_contact` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`),
  CONSTRAINT `fk_account_personnel` FOREIGN KEY (`personnel_id`) REFERENCES `personnel` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11957 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: calendar_holidays
CREATE TABLE `calendar_holidays` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `holiday_date` date NOT NULL COMMENT 'Tatil tarihi',
  `year` int(11) NOT NULL COMMENT 'Yıl',
  `name` varchar(200) NOT NULL COMMENT 'Tatil adı',
  `type` enum('RESMI_TATIL','DINI_BAYRAM','OZEL') DEFAULT 'RESMI_TATIL' COMMENT 'Tatil tipi',
  `is_paid` tinyint(1) DEFAULT 1 COMMENT 'Ücretli tatil mi?',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_holiday_date` (`holiday_date`),
  KEY `idx_holiday_year` (`year`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Resmi tatil ve bayram günleri';

-- Table: contacts
CREATE TABLE `contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `tax_number` varchar(20) DEFAULT NULL,
  `tax_office` varchar(100) DEFAULT NULL,
  `contact_type` enum('Tedarikçi','Taşeron','Ana Firma','İş Ortağı') DEFAULT 'Tedarikçi',
  `is_active` tinyint(1) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `code` varchar(20) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `district` varchar(100) DEFAULT NULL,
  `phone2` varchar(50) DEFAULT NULL,
  `website` varchar(200) DEFAULT NULL,
  `postal_code` varchar(10) DEFAULT NULL,
  `country` varchar(100) DEFAULT 'TÜRKİYE',
  `invoice_address` varchar(500) DEFAULT NULL,
  `invoice_city` varchar(100) DEFAULT NULL,
  `invoice_district` varchar(100) DEFAULT NULL,
  `contact_person` varchar(200) DEFAULT NULL,
  `contact_person_phone` varchar(50) DEFAULT NULL,
  `contact_person_email` varchar(100) DEFAULT NULL,
  `contact_person_title` varchar(100) DEFAULT NULL,
  `sector` varchar(100) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `customer_group` varchar(100) DEFAULT NULL,
  `risk_limit` decimal(18,2) DEFAULT 0.00,
  `payment_term_days` int(11) DEFAULT 0,
  `payment_method` varchar(50) DEFAULT 'Havale',
  `discount_rate` decimal(5,2) DEFAULT 0.00,
  `bank_name` varchar(100) DEFAULT NULL,
  `bank_branch` varchar(100) DEFAULT NULL,
  `bank_account_no` varchar(50) DEFAULT NULL,
  `iban` varchar(34) DEFAULT NULL,
  `swift` varchar(11) DEFAULT NULL,
  `current_balance` decimal(18,2) DEFAULT 0.00,
  `notes` text DEFAULT NULL,
  `private_notes` text DEFAULT NULL,
  `first_transaction_date` date DEFAULT NULL,
  `last_transaction_date` date DEFAULT NULL,
  `manually_edited` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_contacts_tax_number` (`tax_number`),
  UNIQUE KEY `code` (`code`),
  KEY `ix_contacts_name` (`name`),
  KEY `ix_contacts_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7668 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: cost_centers
CREATE TABLE `cost_centers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL,
  `name` varchar(200) NOT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `bolum_adi` varchar(200) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_cost_centers_code` (`code`),
  KEY `ix_cost_centers_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: document_types
CREATE TABLE `document_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL COMMENT 'K??sa kod (??r: SATIS_FATURA)',
  `name` varchar(100) NOT NULL COMMENT 'Tam a????klama (??r: Sat???? Faturas??)',
  `category` varchar(50) NOT NULL COMMENT 'Kategori: FATURA, KASA, BANKA, PERSONEL, VERGI, DIGER',
  `is_active` tinyint(1) DEFAULT 1,
  `sort_order` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `requires_subtype` tinyint(1) DEFAULT 0 COMMENT 'Alt evrak türü seçimi zorunlu mu?',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  UNIQUE KEY `name` (`name`),
  KEY `idx_category` (`category`),
  KEY `idx_active` (`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: einvoices
CREATE TABLE `einvoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `xml_file_path` varchar(500) DEFAULT NULL,
  `xml_hash` varchar(64) DEFAULT NULL,
  `invoice_category` varchar(50) DEFAULT 'incoming' COMMENT 'incoming/outgoing/incoming-archive/outgoing-archive',
  `invoice_uuid` varchar(36) NOT NULL COMMENT 'cbc:UUID - Fatura ETTN',
  `invoice_number` varchar(50) NOT NULL COMMENT 'cbc:ID - Fatura numarasi',
  `invoice_profile` varchar(100) DEFAULT NULL COMMENT 'cbc:ProfileID - TEMELFATURA, TICARIFATURA, EARSIVFATURA',
  `invoice_type` varchar(50) DEFAULT NULL COMMENT 'cbc:InvoiceTypeCode - SATIS, IADE, TEVKIFAT',
  `issue_date` date NOT NULL COMMENT 'cbc:IssueDate - Duzenlenme tarihi',
  `issue_time` time DEFAULT NULL COMMENT 'cbc:IssueTime - Duzenlenme saati',
  `tax_point_date` date DEFAULT NULL COMMENT 'cbc:TaxPointDate - Vergilendirme tarihi',
  `signing_time` timestamp NULL DEFAULT NULL COMMENT 'SigningTime - Fatura imzalanma zamani (XML SigningTime)',
  `supplier_tax_number` varchar(11) DEFAULT NULL COMMENT 'VKN/TCKN - Satici vergi kimlik no',
  `supplier_id_scheme` varchar(10) DEFAULT NULL COMMENT 'VKN veya TCKN',
  `supplier_name` varchar(255) DEFAULT NULL COMMENT 'Satici unvan',
  `supplier_address` text DEFAULT NULL COMMENT 'Satici adres',
  `supplier_city` varchar(100) DEFAULT NULL COMMENT 'Satici sehir',
  `supplier_district` varchar(100) DEFAULT NULL COMMENT 'Satici ilce',
  `supplier_postal_code` varchar(10) DEFAULT NULL COMMENT 'Satici posta kodu',
  `supplier_tax_office` varchar(100) DEFAULT NULL COMMENT 'Satici vergi dairesi',
  `supplier_email` varchar(255) DEFAULT NULL COMMENT 'Satici e-posta',
  `supplier_phone` varchar(20) DEFAULT NULL COMMENT 'Satici telefon',
  `customer_tax_number` varchar(11) DEFAULT NULL COMMENT 'VKN/TCKN - Alici vergi kimlik no',
  `customer_name` varchar(255) DEFAULT NULL COMMENT 'Alici unvan',
  `line_extension_amount` decimal(18,2) DEFAULT NULL COMMENT 'cbc:LineExtensionAmount - Mal hizmet toplam tutari',
  `tax_exclusive_amount` decimal(18,2) DEFAULT NULL COMMENT 'cbc:TaxExclusiveAmount - Vergiler haric tutar',
  `tax_inclusive_amount` decimal(18,2) DEFAULT NULL COMMENT 'cbc:TaxInclusiveAmount - Vergiler dahil tutar',
  `payable_amount` decimal(18,2) DEFAULT NULL COMMENT 'cbc:PayableAmount - Odenecek tutar',
  `allowance_total` decimal(18,2) DEFAULT NULL COMMENT 'Toplam indirim',
  `charge_total` decimal(18,2) DEFAULT NULL COMMENT 'Toplam artirim',
  `total_tax_amount` decimal(18,2) DEFAULT NULL COMMENT 'KDV toplami',
  `withholding_tax_amount` decimal(18,2) DEFAULT NULL COMMENT 'Tevkifat tutari',
  `withholding_percent` decimal(5,2) DEFAULT NULL COMMENT 'Tevkifat orani',
  `withholding_code` varchar(10) DEFAULT NULL COMMENT 'Tevkifat kodu',
  `contact_id` int(11) DEFAULT NULL COMMENT 'contacts tablosu ile iliski',
  `transaction_id` int(11) DEFAULT NULL COMMENT 'transactions tablosu ile iliski',
  `imported_by` int(11) DEFAULT NULL COMMENT 'Import eden kullanici',
  `processing_status` varchar(50) DEFAULT 'IMPORTED' COMMENT 'IMPORTED, MATCHED, TRANSACTION_CREATED, ERROR',
  `error_message` text DEFAULT NULL COMMENT 'Hata mesaji',
  `raw_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Orijinal XML verisi JSON formatinda' CHECK (json_valid(`raw_data`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `currency_code` varchar(3) DEFAULT 'TRY' COMMENT 'Para birimi kodu',
  `exchange_rate` decimal(10,4) DEFAULT NULL COMMENT 'Doviz kuru',
  `cost_center_id` int(11) DEFAULT NULL COMMENT 'Maliyet merkezi ID',
  `supplier_iban` varchar(34) DEFAULT NULL COMMENT 'Satici IBAN numarasi (PayeeFinancialAccount/ID)',
  `pdf_path` varchar(500) DEFAULT NULL COMMENT 'PDF dosyasýnýn relative path''i',
  `has_xml` tinyint(1) DEFAULT 1 COMMENT 'XML dosyasý var mý?',
  `source` varchar(50) DEFAULT 'xml' COMMENT 'Kaynak: xml, pdf_only',
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_uuid` (`invoice_uuid`),
  UNIQUE KEY `idx_einvoices_uuid_unique` (`invoice_uuid`),
  KEY `imported_by` (`imported_by`),
  KEY `idx_einvoices_invoice_number` (`invoice_number`),
  KEY `idx_einvoices_invoice_uuid` (`invoice_uuid`),
  KEY `idx_einvoices_supplier_tax_number` (`supplier_tax_number`),
  KEY `idx_einvoices_issue_date` (`issue_date`),
  KEY `idx_einvoices_contact_id` (`contact_id`),
  KEY `idx_einvoices_transaction_id` (`transaction_id`),
  KEY `idx_einvoices_processing_status` (`processing_status`),
  KEY `idx_einvoices_xml_hash` (`xml_hash`),
  KEY `idx_einvoices_invoice_category` (`invoice_category`),
  KEY `idx_einvoices_created_at` (`created_at`),
  KEY `idx_einvoices_cost_center` (`cost_center_id`),
  KEY `idx_einvoices_supplier_iban` (`supplier_iban`),
  KEY `idx_einvoices_signing_time` (`signing_time`),
  KEY `idx_einvoices_pdf_path` (`pdf_path`),
  KEY `idx_einvoices_has_xml` (`has_xml`),
  CONSTRAINT `einvoices_ibfk_1` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `einvoices_ibfk_2` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `einvoices_ibfk_3` FOREIGN KEY (`imported_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_einvoices_cost_center` FOREIGN KEY (`cost_center_id`) REFERENCES `cost_centers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=3539 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='E-Fatura kayitlari (UBL-TR 1.2 semasi)';

-- Table: icra_takip
CREATE TABLE `icra_takip` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `personnel_id` int(11) NOT NULL,
  `dosya_no` varchar(100) NOT NULL,
  `mahkeme` varchar(200) DEFAULT NULL,
  `toplam_tutar` decimal(18,2) NOT NULL,
  `odenen_tutar` decimal(18,2) DEFAULT NULL,
  `kalan_tutar` decimal(18,2) NOT NULL,
  `sira_no` int(11) DEFAULT NULL,
  `is_active` int(11) DEFAULT NULL,
  `baslangic_tarihi` date DEFAULT NULL,
  `bitis_tarihi` date DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `ix_icra_personnel_sira` (`personnel_id`,`sira_no`),
  KEY `ix_icra_takip_id` (`id`),
  KEY `ix_icra_takip_personnel_id` (`personnel_id`),
  CONSTRAINT `icra_takip_ibfk_1` FOREIGN KEY (`personnel_id`) REFERENCES `personnel` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: invoice_taxes
CREATE TABLE `invoice_taxes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `einvoice_id` int(11) NOT NULL COMMENT 'Bağlı olduğu fatura',
  `tax_type_code` varchar(10) NOT NULL COMMENT 'Vergi kodu (0015=KDV, 4081=ÖİV, 8006=Telsiz, 9040=ÖTV vb)',
  `tax_name` varchar(100) NOT NULL COMMENT 'Vergi adı (Katma Değer Vergisi, Özel İletişim Vergisi vb)',
  `tax_percent` decimal(5,2) NOT NULL COMMENT 'Vergi oranı (%0, %1, %8, %10, %18, %20 vb)',
  `taxable_amount` decimal(18,2) NOT NULL COMMENT 'Matrah tutarı (TaxableAmount)',
  `tax_amount` decimal(18,2) NOT NULL COMMENT 'Hesaplanan vergi tutarı (TaxAmount)',
  `currency_code` varchar(3) DEFAULT NULL COMMENT 'Para birimi (genelde TRY)',
  `exemption_reason_code` varchar(10) DEFAULT NULL COMMENT 'Vergi istisna kodu (varsa)',
  `exemption_reason` varchar(255) DEFAULT NULL COMMENT 'Vergi istisna sebebi (varsa)',
  PRIMARY KEY (`id`),
  KEY `ix_invoice_taxes_id` (`id`),
  KEY `ix_invoice_taxes_einvoice_id` (`einvoice_id`),
  KEY `ix_invoice_taxes_tax_type_code` (`tax_type_code`),
  CONSTRAINT `invoice_taxes_ibfk_1` FOREIGN KEY (`einvoice_id`) REFERENCES `einvoices` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3979 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: invoice_transaction_mappings
CREATE TABLE `invoice_transaction_mappings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `einvoice_id` int(11) NOT NULL,
  `transaction_id` int(11) NOT NULL,
  `document_number` varchar(100) DEFAULT NULL,
  `mapping_type` enum('auto','manual') DEFAULT 'auto',
  `confidence_score` decimal(3,2) DEFAULT 1.00,
  `mapped_by` int(11) DEFAULT NULL,
  `mapped_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `notes` text DEFAULT NULL,
  `payment_amount` decimal(18,2) DEFAULT NULL COMMENT 'Bu fiş ile yapılan ödeme tutarı (NULL = ödeme değil, sadece muhasebe ilişkisi)',
  `payment_date` date DEFAULT NULL COMMENT 'Ödeme tarihi (transaction.transaction_date cache)',
  `payment_status` enum('pending','completed','cancelled') DEFAULT 'completed' COMMENT 'Ödeme durumu (opsiyonel)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_mapping` (`einvoice_id`,`transaction_id`),
  KEY `idx_einvoice` (`einvoice_id`),
  KEY `idx_transaction` (`transaction_id`),
  KEY `idx_document` (`document_number`),
  KEY `idx_mapping_type` (`mapping_type`),
  KEY `idx_payment_amount` (`payment_amount`),
  KEY `idx_payment_date` (`payment_date`),
  KEY `idx_payment_status` (`payment_status`),
  KEY `idx_einvoice_payment` (`einvoice_id`,`payment_amount`),
  CONSTRAINT `invoice_transaction_mappings_ibfk_1` FOREIGN KEY (`einvoice_id`) REFERENCES `einvoices` (`id`) ON DELETE CASCADE,
  CONSTRAINT `invoice_transaction_mappings_ibfk_2` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2971 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fatura-Fiş ilişkileri ve ödeme takibi - payment_amount NULL ise sadece ilişki, dolu ise ödeme kaydı';

-- Table: luca_bordro
CREATE TABLE `luca_bordro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `yil` int(11) NOT NULL,
  `ay` int(11) NOT NULL,
  `donem` varchar(7) NOT NULL,
  `sira_no` int(11) DEFAULT NULL,
  `adi_soyadi` varchar(200) NOT NULL,
  `tckn` varchar(11) NOT NULL,
  `personnel_id` int(11) DEFAULT NULL,
  `ssk_sicil_no` varchar(20) DEFAULT NULL,
  `giris_t` date DEFAULT NULL,
  `cikis_t` date DEFAULT NULL,
  `t_gun` int(11) DEFAULT NULL,
  `nor_kazanc` decimal(18,2) DEFAULT NULL,
  `dig_kazanc` decimal(18,2) DEFAULT NULL,
  `top_kazanc` decimal(18,2) DEFAULT NULL,
  `ssk_m` decimal(18,2) DEFAULT NULL,
  `g_v_m` decimal(18,2) DEFAULT NULL,
  `ssk_isci` decimal(18,2) DEFAULT NULL,
  `iss_p_isci` decimal(18,2) DEFAULT NULL,
  `gel_ver` decimal(18,2) DEFAULT NULL,
  `damga_v` decimal(18,2) DEFAULT NULL,
  `ozel_kesinti` decimal(18,2) DEFAULT NULL,
  `oto_kat_bes` decimal(18,2) DEFAULT NULL,
  `icra` decimal(18,2) DEFAULT NULL,
  `avans` decimal(18,2) DEFAULT NULL,
  `n_odenen` decimal(18,2) DEFAULT NULL,
  `isveren_maliyeti` decimal(18,2) DEFAULT NULL,
  `ssk_isveren` decimal(18,2) DEFAULT NULL,
  `iss_p_isveren` decimal(18,2) DEFAULT NULL,
  `kanun` varchar(10) DEFAULT NULL,
  `ssk_tesviki` decimal(18,2) DEFAULT NULL,
  `upload_date` timestamp NULL DEFAULT current_timestamp(),
  `file_name` varchar(500) DEFAULT NULL,
  `is_processed` int(11) DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `monthly_personnel_records_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_luca_bordro_donem` (`donem`),
  KEY `ix_luca_bordro_yil` (`yil`),
  KEY `ix_luca_bordro_ise_giris_tarihi` (`giris_t`),
  KEY `ix_luca_bordro_id` (`id`),
  KEY `ix_luca_bordro_tckn` (`tckn`),
  KEY `ix_luca_bordro_ay` (`ay`),
  KEY `ix_luca_donem_tckn` (`donem`,`tckn`),
  KEY `ix_luca_donem_giris` (`donem`,`giris_t`),
  KEY `idx_lb_monthly_records` (`monthly_personnel_records_id`),
  KEY `idx_lb_personnel` (`personnel_id`),
  CONSTRAINT `fk_lb_monthly_records` FOREIGN KEY (`monthly_personnel_records_id`) REFERENCES `monthly_personnel_records` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_lb_personnel` FOREIGN KEY (`personnel_id`) REFERENCES `personnel` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1064 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: monthly_personnel_records
CREATE TABLE `monthly_personnel_records` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `personnel_id` int(11) NOT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `donem` varchar(7) NOT NULL COMMENT 'YYYY-MM format (örn: 2025-10)',
  `yil` int(11) DEFAULT NULL,
  `ay` int(11) DEFAULT NULL,
  `adi` varchar(100) DEFAULT NULL,
  `soyadi` varchar(100) DEFAULT NULL,
  `tc_kimlik_no` varchar(11) DEFAULT NULL,
  `cinsiyeti` varchar(10) DEFAULT NULL,
  `bolum` varchar(200) DEFAULT NULL,
  `ssk_no` varchar(50) DEFAULT NULL,
  `cost_center_id` int(11) DEFAULT NULL COMMENT 'Maliyet merkezi ID',
  `ise_giris_tarihi` date DEFAULT NULL COMMENT 'Dönem içi giriş tarihi',
  `isten_cikis_tarihi` date DEFAULT NULL COMMENT 'Dönem içi çıkış tarihi',
  `isten_ayrilis_kodu` varchar(20) DEFAULT NULL,
  `isten_ayrilis_nedeni` varchar(200) DEFAULT NULL,
  `adres` text DEFAULT NULL,
  `telefon` varchar(50) DEFAULT NULL,
  `banka_sube_adi` varchar(100) DEFAULT NULL,
  `hesap_no` varchar(34) DEFAULT NULL,
  `dogum_tarihi` date DEFAULT NULL COMMENT 'Doğum tarihi',
  `nufus_cuzdani_no` varchar(20) DEFAULT NULL,
  `nufusa_kayitli_oldugu_il` varchar(100) DEFAULT NULL,
  `nufusa_kayitli_oldugu_ilce` varchar(100) DEFAULT NULL,
  `nufusa_kayitli_oldugu_mah` varchar(200) DEFAULT NULL,
  `cilt_no` varchar(20) DEFAULT NULL,
  `sira_no` varchar(20) DEFAULT NULL,
  `kutuk_no` varchar(20) DEFAULT NULL,
  `calisilan_gun` int(11) DEFAULT 0 COMMENT 'Çalışılan gün sayısı',
  `ucret` decimal(18,2) DEFAULT NULL COMMENT 'Sicil ücreti',
  `net_brut` varchar(10) DEFAULT NULL,
  `kan_grubu` varchar(5) DEFAULT NULL,
  `isyeri` varchar(200) DEFAULT NULL COMMENT 'Luca işyeri adı',
  `unvan` varchar(200) DEFAULT NULL COMMENT 'Ünvan/Pozisyon',
  `meslek_adi` varchar(200) DEFAULT NULL COMMENT 'Meslek adı',
  `meslek_kodu` varchar(20) DEFAULT NULL COMMENT 'Luca meslek kodu',
  `baba_adi` varchar(100) DEFAULT NULL,
  `anne_adi` varchar(100) DEFAULT NULL,
  `dogum_yeri` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_personnel_donem_bolum_giris` (`personnel_id`,`donem`,`bolum`,`ise_giris_tarihi`),
  KEY `idx_monthly_personnel_donem` (`donem`),
  KEY `idx_monthly_personnel_personnel_id` (`personnel_id`),
  KEY `idx_monthly_personnel_cost_center` (`cost_center_id`),
  KEY `idx_monthly_personnel_dogum_tarihi` (`dogum_tarihi`),
  KEY `idx_monthly_personnel_meslek_kodu` (`meslek_kodu`),
  KEY `idx_mpr_contract_id` (`contract_id`),
  KEY `idx_mpr_yil` (`yil`),
  KEY `idx_mpr_ay` (`ay`),
  KEY `idx_mpr_tc_kimlik_no` (`tc_kimlik_no`),
  KEY `idx_mpr_meslek_kodu` (`meslek_kodu`),
  CONSTRAINT `fk_monthly_personnel_cost_center` FOREIGN KEY (`cost_center_id`) REFERENCES `cost_centers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_monthly_personnel_personnel` FOREIGN KEY (`personnel_id`) REFERENCES `personnel` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_mpr_contract` FOREIGN KEY (`contract_id`) REFERENCES `personnel_contracts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=5338 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Aylık personel sicil kayıtları (Luca import)';

-- Table: monthly_puantaj
CREATE TABLE `monthly_puantaj` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `yil` int(11) NOT NULL,
  `ay` int(11) NOT NULL,
  `donem` varchar(7) NOT NULL,
  `personnel_id` int(11) NOT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `cost_center_id` int(11) DEFAULT NULL,
  `tckn` varchar(11) NOT NULL,
  `adi_soyadi` varchar(200) NOT NULL,
  `santiye_adi` varchar(200) DEFAULT NULL,
  `normal_gun` decimal(5,2) DEFAULT NULL,
  `fazla_mesai_saat` decimal(7,2) DEFAULT NULL,
  `tatil_mesai_gun` decimal(5,2) DEFAULT NULL,
  `yillik_izin_gun` decimal(5,2) DEFAULT NULL,
  `rapor_gun` decimal(5,2) DEFAULT NULL,
  `hafta_tatili_gun` decimal(5,2) DEFAULT NULL,
  `toplam_gun` decimal(5,2) DEFAULT NULL,
  `upload_date` timestamp NULL DEFAULT current_timestamp(),
  `file_name` varchar(500) DEFAULT NULL,
  `is_processed` int(11) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `contract_id` (`contract_id`),
  KEY `cost_center_id` (`cost_center_id`),
  KEY `ix_puantaj_donem_tckn` (`donem`,`tckn`),
  KEY `ix_monthly_puantaj_donem` (`donem`),
  KEY `ix_monthly_puantaj_tckn` (`tckn`),
  KEY `ix_monthly_puantaj_yil` (`yil`),
  KEY `ix_puantaj_donem_santiye` (`donem`,`cost_center_id`),
  KEY `ix_monthly_puantaj_id` (`id`),
  KEY `ix_monthly_puantaj_personnel_id` (`personnel_id`),
  KEY `ix_monthly_puantaj_ay` (`ay`),
  CONSTRAINT `monthly_puantaj_ibfk_1` FOREIGN KEY (`personnel_id`) REFERENCES `personnel` (`id`),
  CONSTRAINT `monthly_puantaj_ibfk_2` FOREIGN KEY (`contract_id`) REFERENCES `personnel_contracts` (`id`),
  CONSTRAINT `monthly_puantaj_ibfk_3` FOREIGN KEY (`cost_center_id`) REFERENCES `cost_centers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: payroll_calculations
CREATE TABLE `payroll_calculations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `yil` int(11) NOT NULL,
  `ay` int(11) NOT NULL,
  `donem` varchar(7) NOT NULL,
  `personnel_id` int(11) NOT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `draft_contract_id` int(11) DEFAULT NULL,
  `luca_bordro_id` int(11) DEFAULT NULL,
  `puantaj_id` int(11) DEFAULT NULL,
  `tckn` varchar(11) NOT NULL,
  `adi_soyadi` varchar(200) NOT NULL,
  `cost_center_id` int(11) DEFAULT NULL,
  `maliyet_merkezi` varchar(200) DEFAULT NULL,
  `ucret_nevi` varchar(20) DEFAULT NULL,
  `kanun_tipi` varchar(10) DEFAULT NULL,
  `maas1_net_odenen` decimal(18,2) DEFAULT NULL,
  `maas1_icra` decimal(18,2) DEFAULT NULL,
  `maas1_bes` decimal(18,2) DEFAULT NULL,
  `maas1_avans` decimal(18,2) DEFAULT NULL,
  `maas1_gelir_vergisi` decimal(18,2) DEFAULT NULL,
  `maas1_damga_vergisi` decimal(18,2) DEFAULT NULL,
  `maas1_ssk_isci` decimal(18,2) DEFAULT NULL,
  `maas1_issizlik_isci` decimal(18,2) DEFAULT NULL,
  `maas1_ssk_isveren` decimal(18,2) DEFAULT NULL,
  `maas1_issizlik_isveren` decimal(18,2) DEFAULT NULL,
  `maas1_ssk_tesviki` decimal(18,2) DEFAULT NULL,
  `maas2_anlaşilan` decimal(18,2) DEFAULT NULL,
  `maas2_normal_calismasi` decimal(18,2) DEFAULT 0.00 COMMENT 'Normal çalışma ücreti',
  `maas2_hafta_tatili` decimal(18,2) DEFAULT NULL,
  `maas2_toplam` decimal(18,2) DEFAULT NULL,
  `normal_gun` decimal(5,2) DEFAULT NULL,
  `hafta_tatili_gun` decimal(5,2) DEFAULT NULL,
  `fazla_mesai_saat` decimal(7,2) DEFAULT NULL,
  `tatil_mesai_gun` decimal(5,2) DEFAULT NULL,
  `yillik_izin_gun` decimal(5,2) DEFAULT NULL,
  `elden_ucret_yuvarlanmis` decimal(18,2) DEFAULT NULL,
  `elden_yuvarlama` decimal(18,2) DEFAULT NULL,
  `elden_yuvarlama_yon` varchar(10) DEFAULT NULL COMMENT 'YUKARI veya ASAGI',
  `account_code_335` varchar(20) DEFAULT NULL,
  `yevmiye_tipi` varchar(10) DEFAULT NULL,
  `transaction_id` int(11) DEFAULT NULL,
  `fis_no` varchar(50) DEFAULT NULL,
  `is_approved` int(11) DEFAULT NULL,
  `is_exported` int(11) DEFAULT NULL,
  `has_error` int(11) DEFAULT NULL,
  `error_message` varchar(1000) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp(),
  `calculated_by` int(11) DEFAULT NULL,
  `approved_by` int(11) DEFAULT NULL,
  `maas2_fm_calismasi` decimal(18,2) DEFAULT 0.00 COMMENT 'Fazla mesai ücreti (ppg.fazla_calismasi * gunluk_ucret/8)',
  `maas2_resmi_tatil` decimal(18,2) DEFAULT 0.00 COMMENT 'Resmi tatil ücreti',
  `maas2_tatil_calismasi` decimal(18,2) DEFAULT 0.00 COMMENT 'Tatil çalışması ücreti',
  `maas2_toplam_tatil_calismasi` decimal(18,2) DEFAULT 0.00 COMMENT 'Toplam tail calismasi (H+T+M)',
  `maas2_yillik_izin` decimal(18,2) DEFAULT 0.00 COMMENT 'Yıllık izin ücreti',
  `maas2_yol` decimal(18,2) DEFAULT 0.00 COMMENT 'Yol parası (ppg.yol)',
  `maas2_prim` decimal(18,2) DEFAULT 0.00 COMMENT 'Prim (ppg.prim)',
  `maas2_ikramiye` decimal(18,2) DEFAULT 0.00 COMMENT 'İkramiye (ppg.ikramiye)',
  `maas2_bayram` decimal(18,2) DEFAULT 0.00 COMMENT 'Bayram harçlığı (ppg.bayram)',
  `maas2_kira` decimal(18,2) DEFAULT 0.00 COMMENT 'Kira yardımı (ppg.kira)',
  `elden_ucret_ham` decimal(18,2) DEFAULT 0.00 COMMENT 'Yuvarlama öncesi ham elden ücret (maas2_toplam - luca_net)',
  `eksik_mesai_saat` decimal(10,2) DEFAULT 0.00 COMMENT 'Eksik Mesai Saat',
  `maas2_em_calismasi` decimal(10,2) DEFAULT 0.00 COMMENT 'Maaş2 EM Çalışması',
  PRIMARY KEY (`id`),
  KEY `contract_id` (`contract_id`),
  KEY `luca_bordro_id` (`luca_bordro_id`),
  KEY `cost_center_id` (`cost_center_id`),
  KEY `transaction_id` (`transaction_id`),
  KEY `ix_payroll_calculations_yil` (`yil`),
  KEY `ix_payroll_donem_santiye` (`donem`,`cost_center_id`),
  KEY `ix_payroll_calculations_id` (`id`),
  KEY `ix_payroll_calculations_tckn` (`tckn`),
  KEY `ix_payroll_calculations_personnel_id` (`personnel_id`),
  KEY `ix_payroll_calculations_ay` (`ay`),
  KEY `ix_payroll_donem_personnel` (`donem`,`personnel_id`),
  KEY `ix_payroll_calculations_donem` (`donem`),
  KEY `idx_payroll_yevmiye_tipi` (`yevmiye_tipi`),
  KEY `idx_payroll_approved` (`is_approved`),
  KEY `payroll_calculations_ibfk_4` (`puantaj_id`),
  CONSTRAINT `payroll_calculations_ibfk_1` FOREIGN KEY (`personnel_id`) REFERENCES `personnel` (`id`),
  CONSTRAINT `payroll_calculations_ibfk_2` FOREIGN KEY (`contract_id`) REFERENCES `personnel_contracts` (`id`),
  CONSTRAINT `payroll_calculations_ibfk_3` FOREIGN KEY (`luca_bordro_id`) REFERENCES `luca_bordro` (`id`),
  CONSTRAINT `payroll_calculations_ibfk_4` FOREIGN KEY (`puantaj_id`) REFERENCES `personnel_puantaj_grid` (`id`),
  CONSTRAINT `payroll_calculations_ibfk_5` FOREIGN KEY (`cost_center_id`) REFERENCES `cost_centers` (`id`),
  CONSTRAINT `payroll_calculations_ibfk_6` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=897 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: personnel
CREATE TABLE `personnel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tc_kimlik_no` varchar(11) NOT NULL,
  `ad` varchar(100) NOT NULL,
  `soyad` varchar(100) NOT NULL,
  `accounts_id` int(11) DEFAULT NULL,
  `iban` varchar(34) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tc_kimlik_no` (`tc_kimlik_no`),
  KEY `idx_personnel_tc_kimlik_no` (`tc_kimlik_no`),
  KEY `idx_personnel_accounts_id` (`accounts_id`),
  KEY `idx_search_name` (`ad`,`soyad`),
  KEY `idx_tc_kimlik_no` (`tc_kimlik_no`),
  CONSTRAINT `fk_personnel_accounts` FOREIGN KEY (`accounts_id`) REFERENCES `accounts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=3232 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: personnel_contracts
CREATE TABLE `personnel_contracts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `personnel_id` int(11) NOT NULL,
  `personnel_draft_contracts_id` int(11) DEFAULT NULL,
  `tc_kimlik_no` varchar(11) DEFAULT NULL,
  `bolum` varchar(200) DEFAULT NULL,
  `monthly_personnel_records_id` int(11) DEFAULT NULL,
  `ise_giris_tarihi` date DEFAULT NULL,
  `isten_cikis_tarihi` date DEFAULT NULL,
  `kanun_tipi` varchar(50) DEFAULT '05510',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `net_brut` varchar(10) DEFAULT NULL,
  `ucret` decimal(18,2) DEFAULT NULL,
  `iban` varchar(34) DEFAULT NULL,
  `taseron` int(11) DEFAULT 0,
  `taseron_id` int(11) DEFAULT NULL,
  `departman` enum('Ankraj Ekibi','Asfaltlama Ekibi','Bekçi Ekibi','Beton Kesim Ekibi','Demirci Ekibi','Döşeme Ekibi','Elektrikçi Ekibi','Fore Kazık Ekibi','İdare Ekibi','Kalıpçı Ekibi','Kalıpçı Kolon Ekibi','Kaynakçı Ekibi','Merkez Ekibi','Operatör Ekibi','Saha Beton Ekibi','Stajyer Ekibi','Şöför Ekibi','Yıkım Ekibi') DEFAULT NULL,
  `cost_center_id` int(11) DEFAULT NULL,
  `is_active` int(11) DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_personnel_contract` (`personnel_id`),
  KEY `idx_dates` (`ise_giris_tarihi`,`isten_cikis_tarihi`),
  KEY `idx_pc_tc_kimlik_no` (`tc_kimlik_no`),
  KEY `idx_pc_monthly_records` (`monthly_personnel_records_id`),
  KEY `idx_pc_taseron_id` (`taseron_id`),
  KEY `idx_pc_draft_contract_id` (`personnel_draft_contracts_id`),
  KEY `idx_date_range` (`ise_giris_tarihi`,`isten_cikis_tarihi`),
  KEY `idx_personnel_active` (`personnel_id`,`is_active`),
  CONSTRAINT `fk_pc_monthly_records` FOREIGN KEY (`monthly_personnel_records_id`) REFERENCES `monthly_personnel_records` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_pc_taseron` FOREIGN KEY (`taseron_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `personnel_contracts_ibfk_1` FOREIGN KEY (`personnel_id`) REFERENCES `personnel` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2468 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Personel sözleşme ve ücret bilgileri';

-- Table: personnel_draft_contracts
CREATE TABLE `personnel_draft_contracts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `personnel_id` int(11) NOT NULL,
  `tc_kimlik_no` varchar(11) DEFAULT NULL,
  `ucret_nevi` enum('aylik','sabit aylik','gunluk') NOT NULL,
  `net_ucret` decimal(18,2) DEFAULT NULL,
  `fm_orani` decimal(5,2) DEFAULT 1.00,
  `tatil_orani` decimal(5,2) DEFAULT 1.00,
  `cost_center_id` int(11) DEFAULT NULL,
  `calisma_takvimi` enum('atipi','btipi','ctipi') DEFAULT NULL,
  `is_active` int(11) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pdc_personnel_id` (`personnel_id`),
  KEY `idx_pdc_tc_kimlik_no` (`tc_kimlik_no`),
  KEY `idx_pdc_cost_center` (`cost_center_id`),
  KEY `idx_pdc_active` (`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=143 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: personnel_puantaj_grid
CREATE TABLE `personnel_puantaj_grid` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `personnel_id` int(11) NOT NULL,
  `monthly_personnel_records_id` int(11) DEFAULT NULL,
  `donem` varchar(7) NOT NULL COMMENT 'YYYY-MM formatında',
  `yil` int(11) NOT NULL,
  `ay` int(11) NOT NULL,
  `gun_1` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_2` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_3` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_4` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_5` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_6` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_7` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_8` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_9` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_10` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_11` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_12` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_13` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_14` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_15` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_16` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_17` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_18` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_19` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_20` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_21` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_22` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_23` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_24` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_25` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_26` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_27` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_28` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_29` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_30` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `gun_31` enum('N','H','T','İ','S','M','R','E','Y','G','O','K','C') DEFAULT NULL,
  `calisilan_gun_sayisi` int(11) DEFAULT 0 COMMENT 'N, G, O kodlarının toplamı',
  `ssk_gun_sayisi` int(11) DEFAULT 0,
  `yillik_izin_gun` int(11) DEFAULT 0 COMMENT 'S kodlarının toplamı',
  `izin_gun_sayisi` int(11) DEFAULT 0 COMMENT 'İ kodlarının toplamı',
  `rapor_gun_sayisi` int(11) DEFAULT 0 COMMENT 'R kodlarının toplamı',
  `eksik_gun_sayisi` int(11) DEFAULT 0 COMMENT 'E kodlarının toplamı',
  `yarim_gun_sayisi` decimal(3,1) DEFAULT 0.0 COMMENT 'Y, K, C kodlarının toplamı (0.5 olarak)',
  `toplam_gun_sayisi` int(11) DEFAULT 0,
  `normal_calismasi` decimal(5,2) DEFAULT 0.00,
  `fazla_calismasi` decimal(7,2) DEFAULT 0.00,
  `gece_calismasi` decimal(5,2) DEFAULT 0.00,
  `tatil_calismasi` decimal(5,2) DEFAULT 0.00,
  `sigorta_girmedigi` int(11) DEFAULT 0,
  `hafta_tatili` int(11) DEFAULT 0,
  `resmi_tatil` int(11) DEFAULT 0,
  `yol` decimal(10,2) DEFAULT 0.00,
  `prim` decimal(10,2) DEFAULT 0.00,
  `ikramiye` decimal(10,2) DEFAULT 0.00,
  `bayram` decimal(10,2) DEFAULT 0.00,
  `kira` decimal(10,2) DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `fm_gun_1` decimal(4,1) DEFAULT NULL,
  `fm_gun_2` decimal(4,1) DEFAULT NULL,
  `fm_gun_3` decimal(4,1) DEFAULT NULL,
  `fm_gun_4` decimal(4,1) DEFAULT NULL,
  `fm_gun_5` decimal(4,1) DEFAULT NULL,
  `fm_gun_6` decimal(4,1) DEFAULT NULL,
  `fm_gun_7` decimal(4,1) DEFAULT NULL,
  `fm_gun_8` decimal(4,1) DEFAULT NULL,
  `fm_gun_9` decimal(4,1) DEFAULT NULL,
  `fm_gun_10` decimal(4,1) DEFAULT NULL,
  `fm_gun_11` decimal(4,1) DEFAULT NULL,
  `fm_gun_12` decimal(4,1) DEFAULT NULL,
  `fm_gun_13` decimal(4,1) DEFAULT NULL,
  `fm_gun_14` decimal(4,1) DEFAULT NULL,
  `fm_gun_15` decimal(4,1) DEFAULT NULL,
  `fm_gun_16` decimal(4,1) DEFAULT NULL,
  `fm_gun_17` decimal(4,1) DEFAULT NULL,
  `fm_gun_18` decimal(4,1) DEFAULT NULL,
  `fm_gun_19` decimal(4,1) DEFAULT NULL,
  `fm_gun_20` decimal(4,1) DEFAULT NULL,
  `fm_gun_21` decimal(4,1) DEFAULT NULL,
  `fm_gun_22` decimal(4,1) DEFAULT NULL,
  `fm_gun_23` decimal(4,1) DEFAULT NULL,
  `fm_gun_24` decimal(4,1) DEFAULT NULL,
  `fm_gun_25` decimal(4,1) DEFAULT NULL,
  `fm_gun_26` decimal(4,1) DEFAULT NULL,
  `fm_gun_27` decimal(4,1) DEFAULT NULL,
  `fm_gun_28` decimal(4,1) DEFAULT NULL,
  `fm_gun_29` decimal(4,1) DEFAULT NULL,
  `fm_gun_30` decimal(4,1) DEFAULT NULL,
  `fm_gun_31` decimal(4,1) DEFAULT NULL,
  `toplam_fm` decimal(5,1) DEFAULT 0.0,
  `cost_center_id` int(11) DEFAULT NULL,
  `ayin_toplam_gun_sayisi` int(11) DEFAULT 30,
  `maas2_gunluk_kazanc` decimal(10,2) DEFAULT 0.00 COMMENT 'Günlük kazanç (draft contract net_ucret/30)',
  `maas2_normal_kazanc` decimal(10,2) DEFAULT 0.00 COMMENT 'Normal çalışma kazancı',
  `maas2_mesai_kazanc` decimal(10,2) DEFAULT 0.00 COMMENT 'Fazla mesai kazancı',
  `maas2_tatil_kazanc` decimal(10,2) DEFAULT 0.00 COMMENT 'Tatil günleri kazancı (hafta+resmi tatil)',
  `maas2_tatil_mesai_kazanc` decimal(10,2) DEFAULT 0.00 COMMENT 'Tatilde çalışma kazancı (tatil_orani ile)',
  `maas2_toplam_kazanc` decimal(10,2) DEFAULT 0.00 COMMENT 'Toplam maaş2 kazancı (tüm kazançlar + ek ödemeler)',
  `eksik_calismasi` decimal(10,2) DEFAULT 0.00 COMMENT 'Eksik Çalışma',
  `maas2_eksik_kazanc` decimal(10,2) DEFAULT 0.00 COMMENT 'Maaş2 Eksik Kazanç',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_personnel_donem` (`personnel_id`,`donem`),
  KEY `idx_personnel_donem` (`personnel_id`,`donem`),
  KEY `idx_donem` (`donem`),
  KEY `idx_yil_ay` (`yil`,`ay`),
  KEY `idx_cost_center` (`cost_center_id`),
  KEY `idx_ppg_monthly_records` (`monthly_personnel_records_id`),
  CONSTRAINT `fk_ppg_monthly_records` FOREIGN KEY (`monthly_personnel_records_id`) REFERENCES `monthly_personnel_records` (`id`) ON DELETE SET NULL,
  CONSTRAINT `personnel_puantaj_grid_ibfk_1` FOREIGN KEY (`personnel_id`) REFERENCES `personnel` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=423 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Excel benzeri puantaj girişi - her personel-dönem bir satır';

-- Table: system_config
CREATE TABLE `system_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `config_key` varchar(100) NOT NULL,
  `config_value` varchar(500) DEFAULT NULL,
  `config_type` varchar(50) DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_system_config_config_key` (`config_key`),
  KEY `ix_system_config_category` (`category`),
  KEY `ix_system_config_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: tax_bracket
CREATE TABLE `tax_bracket` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `min_amount` decimal(15,2) NOT NULL,
  `max_amount` decimal(15,2) DEFAULT NULL,
  `tax_rate` decimal(5,4) NOT NULL,
  `year` int(11) NOT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `ix_tax_bracket_id` (`id`),
  KEY `ix_tax_bracket_year` (`year`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: tax_codes
CREATE TABLE `tax_codes` (
  `code` varchar(10) NOT NULL COMMENT 'Vergi Kodu (ör: 0015, 4081)',
  `name` varchar(200) NOT NULL COMMENT 'Resmi Vergi Adı',
  `short_name` varchar(50) DEFAULT NULL COMMENT 'Kısa Ad/Kısaltma (ör: KDV GERCEK)',
  `is_withholding` tinyint(1) DEFAULT NULL COMMENT 'Tevkifat kodu mu?',
  `description` varchar(500) DEFAULT NULL COMMENT 'Açıklama',
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: transaction_counter
CREATE TABLE `transaction_counter` (
  `id` int(11) NOT NULL DEFAULT 1,
  `last_number` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: transaction_lines
CREATE TABLE `transaction_lines` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `transaction_id` int(11) NOT NULL,
  `account_id` int(11) NOT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `debit` decimal(18,2) DEFAULT NULL,
  `credit` decimal(18,2) DEFAULT NULL,
  `quantity` decimal(18,4) DEFAULT NULL,
  `unit` varchar(20) DEFAULT NULL,
  `vat_rate` decimal(5,4) DEFAULT NULL,
  `withholding_rate` decimal(5,4) DEFAULT NULL,
  `vat_base` decimal(18,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `contact_id` (`contact_id`),
  KEY `ix_transaction_lines_transaction_id` (`transaction_id`),
  KEY `ix_transaction_lines_id` (`id`),
  KEY `ix_transaction_lines_account_id` (`account_id`),
  CONSTRAINT `transaction_lines_ibfk_1` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`),
  CONSTRAINT `transaction_lines_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`),
  CONSTRAINT `transaction_lines_ibfk_3` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=583858 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: transactions
CREATE TABLE `transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `transaction_number` varchar(50) NOT NULL,
  `transaction_date` date NOT NULL,
  `accounting_period` varchar(7) NOT NULL,
  `cost_center_id` int(11) DEFAULT NULL,
  `personnel_id` int(11) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `document_type_id` int(11) DEFAULT NULL,
  `document_number` varchar(100) DEFAULT NULL,
  `related_invoice_number` varchar(100) DEFAULT NULL,
  `draft` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_transactions_transaction_number` (`transaction_number`),
  KEY `cost_center_id` (`cost_center_id`),
  KEY `ix_transactions_accounting_period` (`accounting_period`),
  KEY `ix_transactions_id` (`id`),
  KEY `ix_transactions_transaction_date` (`transaction_date`),
  KEY `idx_transactions_document_type` (`document_type_id`),
  KEY `idx_transactions_personnel` (`personnel_id`),
  KEY `idx_transactions_date_personnel` (`transaction_date`,`personnel_id`),
  KEY `idx_transactions_period_personnel` (`accounting_period`,`personnel_id`),
  CONSTRAINT `fk_trans_doctype` FOREIGN KEY (`document_type_id`) REFERENCES `document_types` (`id`),
  CONSTRAINT `fk_transactions_document_type` FOREIGN KEY (`document_type_id`) REFERENCES `document_types` (`id`),
  CONSTRAINT `fk_transactions_personnel` FOREIGN KEY (`personnel_id`) REFERENCES `personnel` (`id`) ON DELETE SET NULL,
  CONSTRAINT `transactions_ibfk_1` FOREIGN KEY (`cost_center_id`) REFERENCES `cost_centers` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=91677 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: user_email_settings
CREATE TABLE `user_email_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `smtp_server` varchar(100) DEFAULT 'smtp.gmail.com',
  `smtp_port` int(11) DEFAULT 587,
  `smtp_username` varchar(100) DEFAULT NULL,
  `smtp_password` varchar(200) DEFAULT NULL,
  `use_tls` tinyint(1) DEFAULT 1,
  `default_cc_recipients` varchar(500) DEFAULT NULL COMMENT 'Virgülle ayrılmış default CC alıcıları (muhasebe@firma.com,yonetim@firma.com)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `idx_user_id` (`user_id`),
  CONSTRAINT `user_email_settings_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: users
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `hashed_password` varchar(200) NOT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `role` varchar(50) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `ix_users_username` (`username`),
  KEY `ix_users_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
